APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DCC_SPRITEBATCHNODE_RENDER_SUBPIXEL=0 -DCC_NODE_RENDER_SUBPIXEL=0 -O3 -DNDEBUG -std=c++11
#APP_OPTIM := release
#APP_ABI := armeabi armeabi-v7a
APP_USE_CPP0X := true
#NDK_TOOLCHAIN_VERSION=4.8
